name: eduquest

services:
  db:
    container_name: eduquestDb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 8002:1433
    environment:
      MSSQL_SA_PASSWORD: Password123
      ACCEPT_EULA: Y
    networks:
     - backend
    volumes:
     - db_data:/var/opt/mssql

  server:
    build:
      context: ./EduQuest
      dockerfile: Dockerfile
    container_name: eduquest_server
    ports:
     - 8000:8080
    environment:
      - DB_HOST=db
      - DB_NAME=eduquestdb
      - DB_SA_PASSWORD=Password123
    depends_on:
      - db
    networks:
      - backend
      - frontend

  web:
    build:
      context: ./EduQuestUI
      dockerfile: Dockerfile
    container_name: eduquest_web
    ports:
      - "3000:4173" 
    environment:
      VITE_API_BASE_URL: http://server:8080  # Adjust port if necessary
    depends_on:
      - server
    networks:
      - frontend

  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: eduquest_azurite
    ports:
      - 10000:10000  # Blob service
      - 10001:10001  # Queue service
      - 10002:10002  # Table service
    networks:
      - backend
    volumes:
      - azurite_data:/data

networks:
  backend:
  frontend:

volumes:
  db_data:
  azurite_data:

